server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingservice
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  jpa:
    showSql: true
    hibernate:
      ddlAuto: update

  application:
    name: RATING-SERVICE

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka
    registerWithEureka: true