server:
  port: 8762

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
  application:
    name: USER-SERVICE

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka
    registerWithEureka: true

management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health

resilience4j:
  circuitbreaker:
    instances:
      ratinghotelbreaker:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
